/* Automatically generated by './build/bin/build-entry.js' */

import Country from '../packages/country/index.js'
import Demo from '../packages/demo/index.js'
import locale from './locale'

const components = [
  Country,
  Demo
]

const install = function (Vue, opts = {}) {
  locale.use(opts.locale)
  locale.i18n(opts.i18n)

  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  }
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.3',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  Country,
  Demo
}
